name: Build Stravaig.Gedcom

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.vscode/**'
      - '.gitignore'

  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - '.vscode/**'
      - '.gitignore'

  workflow_dispatch:
    inputs:
      isPublic:
        description: 'Is Public Release'
        required: false
        default: "false"
      isPreview:
        description: 'Is Preview Release'
        required: false
        default: "true"

jobs:     
  build:
    name: Build, Test, and Release
    runs-on: ubuntu-latest
    env:
      STRAVAIG_SOLUTION: ./src/Stravaig.Gedcom.sln
      STRAVAIG_UNIT_TESTS: ./src/**.UnitTests
      STRAVAIG_PACKAGE_PROJECT: src/Stravaig.Gedcom/Stravaig.Gedcom.csproj
      
    steps:
    - uses: actions/checkout@v2
      name: Checking out the source code

    - name: Set version number
      shell: pwsh
      run: ./Set-Version.ps1 -IsPublic "${{ github.event.inputs.isPublic }}" -IsPreview "${{ github.event.inputs.isPreview }}"

    - name: Display workflow state
      run: |
        echo "Package version: $STRAVAIG_PACKAGE_VERSION"
        echo "Version Suffix: $STRAVAIG_PACKAGE_VERSION_SUFFIX"
        echo "Publish To NuGet: $STRAVAIG_PUBLISH_TO_NUGET" 
     
    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: 3.1.402
    
    - name: Build Solution
      run: dotnet build ${{ env.STRAVAIG_SOLUTION }} --configuration Release

    - name: Test solution
      run: dotnet test ${{ env.STRAVAIG_UNIT_TESTS }} --configuration Release
      
    - name: Package Preview Release
      if: ${{ env.STRAVAIG_PACKAGE_VERSION_SUFFIX != '~' }}
      run: dotnet pack ${{ env.STRAVAIG_PACKAGE_PROJECT }} --configuration Release --output ./out --include-symbols --include-source /p:VersionPrefix="$STRAVAIG_PACKAGE_VERSION" --version-suffix "$STRAVAIG_PACKAGE_VERSION_SUFFIX" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Package Stable Release
      if: ${{ env.STRAVAIG_PACKAGE_VERSION_SUFFIX == '~' }}
      run: dotnet pack ${{ env.STRAVAIG_PACKAGE_PROJECT }} --configuration Release --output ./out --include-symbols --include-source /p:VersionPrefix="$STRAVAIG_PACKAGE_VERSION" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Push package to NuGet
      if: ${{ env.STRAVAIG_PUBLISH_TO_NUGET == 'true' }}
      run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.STRAVAIG_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
