name: Build Stravaig.Gedcom

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checking out the source code
      
    - name: Get Environment Info
      run: env

    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: 3.1.101
    
    - name: Test solution
      run: dotnet test src/Stravaig.Gedcom.UnitTests/Stravaig.Gedcom.UnitTests.csproj
      
    - name: Create Preview Packages
      run: dotnet pack src/Stravaig.Gedcom/Stravaig.Gedcom.csproj --configuration Release --include-source --include-symbols --version-suffix preview --output packages
      
    - name: Create Stable Packages
      run: dotnet pack src/Stravaig.Gedcom/Stravaig.Gedcom.csproj --configuration Release --include-source --include-symbols --output packages

    - name: Upload artefacts
      uses: actions/upload-artifact@1.0.0
      with:
        name: packages
        path: packages

  deploy-prerelease:
    needs: build
    runs-on: ubuntu-latest
    # also works with windows-latest and macos-latest
    steps:
    - name: Download artefacts
      uses: actions/download-artifact@v1
      with:
        name: packages
        path: .

    - name: List Artefacts
      run: ls -a -r

    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Stravaig-Projects/index.json -Username Stravaig-Projects -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1
        
    - name: Publish Package
      run: nuget push *-preview.nupkg -Source "GPR"

    - name: Publish Symbols Package
      run: nuget push *-preview.symbols.nupkg -Source "GPR"
